Ashray/Models/BedTypes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ashray.Models
{
	public class BedTypes
	{
		public string CenterName { get; set; }
		public string Location { get; set; }
		public int IsolationBed { get; set; }

		public int Oxygen { get; set; }
		public int ICUBed { get; set; }
	}
}

Ashray/Models/PostHospital.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ashray.Models
{
	public class PostHospital
	{
		public string CenterName { get; set; }
		public string PatientName { get; set; }
		public string RegistrationDate { get; set; }

		public string Gender { get; set; }

		public string Status { get; set; }

		public int PatientId { get; set; }

		public string RTPCRNumber { get; set; }
	}
}

Ashray/Controllers/AshrayController.cs
using Ashray.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ashray.Filter;
using PagedList;
namespace Ashray.Controllers
{
    [CustomAuthenticationFilter]
    public class AshrayController : Controller
    {
        // GET: Ashray
        public ActionResult Index()
        {
            var homeDashboard = Registation.GetHomeDashboard();           
            homeDashboard.PatientDashboard = Registation.GetPatientHomeDashboard();
			return View(homeDashboard);
        }      

        public ActionResult FindHospital()
        {
            var dashboard = Registation.GetDashboard();
            return View(dashboard);
        }

        public ActionResult FindBed()
        {
            return View();
        }

        public ActionResult PostHospital()
        {
            var list = Registation.GetPosthospitalInfo();
            return View(list);
        }

        public ActionResult PostBed()
        {
            return View();
        }

        public ActionResult BedTypes()
        {
            var bedInfo = Registation.GetBedTypeInfo();
            return View(bedInfo);
        }

        public ActionResult PatientRegistration()
        {
            return View();
        }

        public ActionResult ViewPatient(int id, string name, string rtpctr)
        {
            PatientHistory patientHistory = new PatientHistory();
            patientHistory.PatientInfo = new PatientInfo();
            patientHistory.PatientInfo.PatientId = id;
            patientHistory.PatientInfo.PatientName = name;            
            patientHistory.PatientInfo.RTPCRTestNumber = rtpctr;
            var history = Registation.GetPatientHistory(id);
            if (history != null)
            {
                patientHistory.SPO2 = history.SPO2;
                patientHistory.BP = history.BP;
                patientHistory.Temperature = history.Temperature;
                patientHistory.BedNumber = history.BedNumber;
                patientHistory.RoomNumber = history.RoomNumber;
                patientHistory.CheckinDateTime = history.CheckinDateTime;
                patientHistory.CheckoutDatetime = history.CheckoutDatetime;
                patientHistory.DischargeInfo = history.DischargeInfo;
                patientHistory.PatientInfo.EmergencyContactName1 = history.EmergencyContactName1;
                patientHistory.PatientInfo.EmergencyContactNumber1 = history.EmergencyContactNumber1;
                using(var db = new AshrayEntities())
				{
                    var matchedInfo = db.PatientInfoes.FirstOrDefault(x => x.PatientId == id);
                    if(matchedInfo!=null)
					{
                        patientHistory.PatientInfo.EmergencyContactName1 = matchedInfo.EmergencyContactName1;
                        patientHistory.PatientInfo.EmergencyContactNumber1 = matchedInfo.EmergencyContactNumber1;
                        patientHistory.PatientInfo.GovtIdNumber = matchedInfo.GovtIdNumber;
                    }
				}
            }
            patientHistory.Files = new List<FileUpload>();
            string foldername = patientHistory.PatientInfo.PatientId + "_" + patientHistory.PatientInfo.PatientName;
            string pathname = Server.MapPath("~/UploadedFiles/") + foldername; // Give the specific path
            if (Directory.Exists(pathname))
            {
                var fileInfo = Directory.GetFiles(pathname);
                if (fileInfo.Length > 0)
                {
                    foreach (var item in fileInfo)
                    {
                        var file = new FileUpload();
                        file.FileId = patientHistory.PatientInfo.PatientId.ToString();
                        file.FileName = Path.GetFileName(item);
                        file.FileUrl = patientHistory.PatientInfo.PatientId + "_" + patientHistory.PatientInfo.PatientName + System.IO.Path.DirectorySeparatorChar + Path.GetFileName(item);
                        patientHistory.Files.Add(file);
                    }
                }

            }
            return View(patientHistory);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        public ActionResult Registration(Registation registation)
        {
            var res = Registation.InsertRegistration(registation);
            return View();
        }

        [HttpPost]
        public ActionResult PatientRegistration(PatientInfo patientInfo)
        {
            var res = Registation.InsertPatientInfo(patientInfo);
            return RedirectToAction("FindHospital");
        }

		public ActionResult Delete(int id)
		{
			int patientStatus = 1;
			Registation.DeletePatientInfo(id, patientStatus);
			return RedirectToAction("PostHospital");
		}

        public ActionResult ToHospital(int id)
        {
            int patientStatus = 2;
            Registation.DeletePatientInfo(id, patientStatus);
            return RedirectToAction("PostHospital");
        }

        [HttpPost]
        public ActionResult ViewPatient(PatientHistory ph, IEnumerable<HttpPostedFileBase> files)
        {

            string foldername = ph.PatientInfo.PatientId + "_" + ph.PatientInfo.PatientName;
            string pathname = Server.MapPath("~/UploadedFiles/") + foldername;  // Give the specific path  
            if (!(Directory.Exists(pathname)))
            {
                Directory.CreateDirectory(pathname);
            }
            if (files != null)
            {
                foreach (var file in files)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(pathname, fileName);
                        file.SaveAs(path);
                    }
                }
            }
            var res = Registation.InsertPatientHistory(ph);
            return RedirectToAction("PostHospital");
        }

        public FileResult Download(string id)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(Server.MapPath("~/UploadedFiles/") + id);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, id);
        }
        

    }
}

Ashray/Views/Ashray/BedTypes.cshtml
@model IEnumerable<Ashray.Models.BedTypes>
@{
    ViewBag.Title = "BedTypes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Available <span class="text-danger">Bed Types</span></h2>

        <ol class="breadcrumb">
            <li>
                <a href="index">Home</a>
            </li>

            <li class="active">
                <strong>Bed Types</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<br>

<div class="ibox-content">
    <div class="row">
        <div class="col-md-12" style="padding-left:20px;">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Available<span class="text-danger"> Beds</span> </h5>

                    </div>
					<div class="ibox-content">

						<table class="table">
							<tr>
								<th>
									@Html.DisplayNameFor(model => model.CenterName)
								</th>
								<th>
									@Html.DisplayNameFor(model => model.Location)
								</th>
								<th>
									@Html.DisplayNameFor(model => model.IsolationBed)
								</th>
								<th>
									@Html.DisplayNameFor(model => model.Oxygen)
								</th>
								<th>
									@Html.DisplayNameFor(model => model.ICUBed)
								</th>							
								<th>Registeration</th>
							</tr>

							@foreach (var item in Model)
							{
								<tr>
									<td>
										@Html.DisplayFor(modelItem => item.CenterName)
									</td>
									<td>
										@Html.DisplayFor(modelItem => item.Location)
									</td>
									<td>
										@Html.DisplayFor(modelItem => item.IsolationBed)
									</td>
									<td>
										@Html.DisplayFor(modelItem => item.Oxygen)
									</td>
									<td>
										@Html.DisplayFor(modelItem => item.ICUBed)
									</td>
									<td class="text-navy">
										<button class="btn btn-sm btn-primary pull-center m-t-n-xs"
												onClick="location.href='@Url.Action("PatientRegistration", "Ashray")'"
												type="submit">
											&nbsp;&nbsp;<strong>
												<i class="fa fa-login"></i>
												&nbsp;Register
											</strong>&nbsp;&nbsp;
										</button>
									</td>
								</tr>
							}
						</table>						
					</div>
                </div>
            </div>
        </div>
    </div>
</div>

Ashray/Views/Ashray/FindHospital.cshtml
@model Ashray.Models.Dashboard
@{
	ViewBag.Title = "FindHospital";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-lg-10">
		<h2>Find <span class="text-danger">a Hospital</span></h2>

		<ol class="breadcrumb">
			<li>
				<a href="index">Home</a>
			</li>

			<li class="active">
				<strong>Post a Hospital</strong>
			</li>
		</ol>
	</div>
	<div class="col-lg-2">

	</div>
</div>
<br>

<div class="ibox-content">
	<div class="row">
		<div class="col-sm-2">

			<div class="row">
				<div class="col-sm-12">
					<div class="form-group">
						<label>State </label> <input placeholder="Select State"
										 class="form-control" type="text">
					</div>
				</div>
				<div class="col-sm-12">
					<div class="form-group">
						<label>Location </label> <input placeholder="Enter Location"
											class="form-control" type="text">
					</div>
				</div>
				<div class="col-sm-12">
					<div class="form-group">
						<label>Pincode </label> <input placeholder="Enter Pincode"
										   class="form-control" type="text">
					</div>
				</div>

				<!-- <div class="col-sm-12">
					<div class="form-group"><label>Radius </label><select name="ddlMaterial"
							id="ddlMaterial" class="form-control">
							<option selected="selected" value="Select">Select</option>
							<option value="45">Within 50 KM</option>
							<option value="18">Within 100 KM</option>
							<option value="4">Within 200 KM</option>
							<option value="16">Within 300 KM</option>
							<option value="6">Within 400 KM</option>
							<option value="6">More than 500</option>
						</select></div>
				</div>
				<div class="col-sm-12">
					<div class="form-group"><label>Date </label>
						<div class="input-group date form_datetime-component">
							<input name="txtDate" maxlength="10" id="txtDate"
								class="form-control hasDatepicker" readonly type="text">
							<span class="input-group-btn">
								<button id="datePicker" class="btn btn-danger date-set" type="button"><i
										class="fa fa-calendar"></i></button>
							</span>
						</div>
					</div>
				</div> -->
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="form-group" align="center">
						<br>
						<button class="btn btn-sm btn-primary pull-center m-t-n-xs"
								type="submit">
							&nbsp;&nbsp;<strong>
								<i class="fa fa-search"></i>
								&nbsp;Search
							</strong>&nbsp;&nbsp;
						</button>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-10" style="padding-left:20px;">
			<div class="col-lg-12">
				<div class="ibox float-e-margins">
					<div class="ibox-title">
						<h5>Available<span class="text-danger"> Hospitals</span> </h5>

					</div>
					<div class="ibox-content">

						<table class="table table-striped">
							<thead>
								<tr class="bg-success">
									<th>Type</th>
									<th>Details</th>
									<th>Location</th>
									<th>Availability</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td><img src="~/Content/img/Img_Hospital.png" width="50" height="30"></td>
									<td>Covid Center</td>
									<td>
										Plot no. 1-90/7/3/55, Street No 4,
										Near  Medicover Hospital,
										Patrika Nagar, Madharpur, Hyderabad-500081
									</td>

									<td class="text-navy">
										<button class="btn btn-sm btn-primary pull-center m-t-n-xs"
												onClick="location.href='@Url.Action("BedTypes", "Ashray")'"
												type="submit">
											<strong>@(Model.BedCount - Model.OccupiedBeds) / @Model.BedCount </strong>
										</button>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Ashray/Views/Ashray/PatientRegistration.cshtml
@model Ashray.PatientInfo
@{
    ViewBag.Title = "PatientRegistration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        var d = new Date();
        var day = d.getDate();
        var month = d.toDateString().substr(4, 3);
        var year = d.getFullYear();
        $("#txtCheckInTime").val(day + "/" + month + "/" + year);
    });
</script>
<link href="~/Content/css/Jquery.css" rel="stylesheet" />
<script type='text/javascript'>
    $(function () {
        $('.date-picker').datepicker();
    })
</script>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Available <span class="text-danger">Bed Types</span></h2>
        <ol class="breadcrumb">
            <li>
                <a href="index">Home</a>
            </li>
            <li class="active">
                <strong>Bed Types</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<br>
<div class="ibox-content">
    <div class="row">
        <div class="col-md-12" style="padding-left:20px;">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Available<span class="text-danger"> Beds</span> </h5>
                    </div>
                    @using (Html.BeginForm("PatientRegistration", "Ashray", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="ibox-content">
                            <br />
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label for="controlCenterName" class="col-form-label col-md-3">Facility Name:</label>
                                    @Html.DropDownList("centerId", new List<SelectListItem>
                                {
                                     new SelectListItem{ Text="Project Ashray", Value = "1" }
                                }, new { @class = "form-control col-md-4 controlWidth" })
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="dateTime" class="col-form-label col-md-3">Date Time:</label>
                                    @Html.TextBoxFor(m => m.DateTime, new { @value = DateTime.Now.ToShortDateString(), @class = "form-control controlWidth", @style = "position:relative", @required = "required", @title = "Please select CheckInTime", @maxlength = "50", @id = "txtCheckInTime" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label for="patientName" class="col-form-label col-md-3">Patient Name:</label>
                                    @Html.TextBoxFor(m => m.PatientName, new { @class = "form-control controlWidth", @style = "position:relative", @required = "required", @title = "Please enter PatientName", @maxlength = "50", @id = "txtPatientName" })
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="result" class="col-form-label col-md-3">Result:</label>
                                    @Html.TextBoxFor(m => m.TestResult, new { @class = "form-control controlWidth", @style = "position:relative", @required = "required", @title = "Please enter TestResult ", @maxlength = "50", @id = "txtTestResult" })
                                </div>
                            </div>
							<div class="row">
								<div class="col-md-6 form-group">
									<label for="rtpcrTestNum" class="col-form-label col-md-3">RTPCR Test Number:</label>
									@Html.TextBoxFor(m => m.RTPCRTestNumber, new { @class = "form-control controlWidth", @style = "position:relative", @required = "required", @title = "Please enter RTPCRTestNumber", @maxlength = "50", @id = "txtRTPCRTestNumber" })
								</div>
								<div class="col-md-6 form-group">
									<label for="gender" class="col-form-label col-md-3">RTPCR Test Date:</label>
									@Html.TextBoxFor(m => m.RTPCRTestDate, new { @class = "form-control date-picker controlWidth", @style = "position:relative", @required = "required", @title = "Please enter RTPCR Test Date", @maxlength = "50", @id = "txtRTPCRTestDate" })
								</div>								
							</div>
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label for="rtpcrTestNum" class="col-form-label col-md-3">Patient Phone Number:</label>
                                    @Html.TextBoxFor(m => m.PatientPhoneNumber, new { @class = "form-control controlWidth", @style = "position:relative", @required = "required", @title = "Please enter Patient Phone Number", @maxlength = "50", @id = "txtPatientPhoneNumber" })
                                </div>
								<div class="col-md-6 form-group">
									<label for="gender" class="col-form-label col-md-3">Gender:</label>									
									@Html.DropDownListFor(m => m.Gender, new SelectList(Enum.GetValues(typeof(Gender))), "Select Gender", new { @class = "form-control controlWidth", @style = "position:relative", @required = "required", @title = "Please enter Gender", @maxlength = "50", @id = "txtGender" })
								</div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label for="governmantId" class="col-form-label col-md-3">Governmant ID:</label>
                                    @Html.TextBoxFor(m => m.GovtIdNumber, new { @class = "form-control controlWidth", @style = "position:relative", @required = "required", @title = "Please enter GovtIdNumber", @maxlength = "50", @id = "txtGovtIdNumber" })
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="address" class="col-form-labelc col-md-3">Address:</label>
                                    @Html.TextBoxFor(m => m.PatientAddress, new { @class = "form-control controlWidth", @style = "position:relative", @required = "required", @title = "Please enter Patient Address", @maxlength = "50", @id = "txtPatientAddress" })
                                </div>
                            </div>
							<div class="row">
								<div class="col-md-4 form-group">
									<label for="attenderName" class="col-form-label col-md-3">Additional Contact Name1:</label>
									@Html.TextBoxFor(m => m.EmergencyContactName1, new { @class = "form-control controlWidth", @style = " position:relative", @required = "required", @title = "Please enter Emergency Contact Name1", @maxlength = "50", @id = "txtEmergencyContactName1" })
								</div>
								<div class="col-md-4 form-group">
									<label for="contactNumber" class="col-form-label col-md-3">Contact Number1:</label>
									@Html.TextBoxFor(m => m.EmergencyContactNumber1, new { @class = "form-control controlWidth", @style = "position:relative", @required = "required", @title = "Please enter Emergency Contact Number1", @maxlength = "50", @id = "txtEmergencyContactNumber1" })
								</div>
								<div class="col-md-4 form-group">
									<label for="attenderName" class="col-form-label col-md-3">Relation ship 1:</label>
									@Html.TextBoxFor(m => m.EmergencyContactRelationShip1, new { @class = "form-control controlWidth", @style = "position:relative", @title = "Please enter Emergency Contact Name2", @maxlength = "20", @id = "txtEmergencyContactRealtionship1" })
								</div>
							</div>
							<div class="row">
								<div class="col-md-4 form-group">
									<label for="attenderName" class="col-form-label col-md-3">Additional Contact Name2:</label>
									@Html.TextBoxFor(m => m.EmergencyContactName2, new { @class = "form-control controlWidth", @style = "position:relative", @required = "required", @title = "Please enter Emergency Contact Name2", @maxlength = "50", @id = "txtEmergencyContactName2" })
								</div>
								<div class="col-md-4 form-group">
									<label for="contactNumber" class="col-form-label col-md-3">Contact Number2:</label>
									@Html.TextBoxFor(m => m.EmergencyContactNumber2, new { @class = "form-control controlWidth", @style = "position:relative", @required = "required", @title = "Please enter Emergency Contact Number2", @maxlength = "50", @id = "txtEmergencyContactNumber2" })
								</div>
								<div class="col-md-4 form-group">
									<label for="contactNumber" class="col-form-label col-md-3">Relation ship 2:</label>
									@Html.TextBoxFor(m => m.EmergencyContactRelationShip2, new { @class = "form-control controlWidth", @style = "position:relative", @title = "Please enter Emergency Contact Number2", @maxlength = "20", @id = "txtEmergencyContactRealtionship2" })
								</div>
							</div>
                            @*<div class="row">
                                <div class="col-md-6 form-group">
                                    <label for="attenderName" class="col-form-label col-md-3">Relation ship 1:</label>
                                    @Html.TextBoxFor(m => m.EmergencyContactRelationShip1, new { @class = "form-control controlWidth", @style = "position:relative", @title = "Please enter Emergency Contact Name2", @maxlength = "20", @id = "txtEmergencyContactRealtionship1" })
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="contactNumber" class="col-form-label col-md-3">Relation ship 2:</label>
                                    @Html.TextBoxFor(m => m.EmergencyContactRelationShip2, new { @class = "form-control controlWidth", @style = "position:relative", @title = "Please enter Emergency Contact Number2", @maxlength = "20", @id = "txtEmergencyContactRealtionship2" })
                                </div>
                            </div>*@
                            @*<div class="row">
                                    <div class="col-md-6 form-group">
                                        <label for="refferedTo" class="col-form-label">Reffered To:</label>
                                        @Html.TextBoxFor(m => m.CentreRegistration.CentreName, new { @style = "position:relative", @required = "required", @title = "Please enter CentreName", @maxlength = "50", @id = "txtCentreName" })
                                        <input type="text" class="form-control" id="refferedTo">
                                    </div>
                                    <div class="col-md-6 form-group">
                                        <label for="bedsAvailable" class="col-form-label">Beds Available:</label>
                                        @Html.TextBoxFor(m => m.CentreRegistration.CentreName, new { @style = "position:relative", @required = "required", @title = "Please enter CentreName", @maxlength = "50", @id = "txtCentreName" })
                                        <input type="text" class="form-control" id="bedsAvailable">
                                    </div>
                                </div>

                                        </div>*@
                            <div class="row">
                                <div class="col-lg-5"></div>
                                <div class="col-lg-12">
                                    <input class="btn btn-sm btn-primary pull-Center m-t-n-xs" type="submit">
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Ashray/Views/Ashray/PostHospital.cshtml
@model IEnumerable<Ashray.Models.PostHospital>
@{
	ViewBag.Title = "PostHospital";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-lg-10">
		<ol class="breadcrumb">
			<li>
				<a href="index">Home</a>
			</li>

			<li class="active">
				<strong>Post a Hospital</strong>
			</li>
		</ol>
	</div>
	<div class="col-lg-2">

	</div>
</div>
<br>
<div class="ibox-content">
    <div class="row">
        <div class="col-md-6 form-group" style="padding-bottom:20px;">
            <div style="padding-top:20px;">
                <label for="gender" class="col-form-label col-lg-3">Facility Name:</label>
                <select name="ddlFacilityName" id="ddlFacilityName" class="form-control col-lg-3" style="width:30%;">
                    <option selected="selected" value="Select">Select</option>
                    <option value="1">KIMS</option>
                    <option value="2">GITAM</option>
                </select>
            </div>
        </div><br /><br />
        <div class="col-md-12 form-group table-bed-details" style="background: white;overflow-y: auto;max-height: 475px;">
            <table class="table table-striped">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CenterName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PatientName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.RegistrationDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Gender)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>Action</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CenterName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PatientName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RegistrationDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Gender)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td class="text-navy">
                            <button class="btn btn-sm btn-primary pull-center m-t-n-xs"
                                    onClick="location.href='@Url.Action("ViewPatient", "Ashray", new {id = item.PatientId,name =item.PatientName,rtpctr = item.RTPCRNumber})'"
                                    type="submit">
                                &nbsp;&nbsp;<strong>
                                    <i class="fa fa-login"></i>
                                    &nbsp;View
                                </strong>&nbsp;&nbsp;
                            </button>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>